### ISSUE TITLE
Ошибка при подключении

### ISSUE THREAD

**Issue by mad** [yandex-cloud/ydb-java-sdk#1]
Взял тест NameResolverExample, поменял эндпоинт и базу, указал токен. Код выполняю с ВМ из облака

Получаю такую ошибку
```
WARNING: [Channel<1>: (ydb://lb.XXX.ydb.mdb.yandexcloud.net:2135/XXX)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Network closed for unknown reason
unable to resolve database /XXX, network issue, cause=null}
Exception in thread "main" com.yandex.ydb.core.UnexpectedResultException: create session, code: TRANSPORT_UNAVAILABLE, issues: [gRPC error: (UNAVAILABLE) Network closed for unknown reason
unable to resolve database /XXX, network issue (S_ERROR)]
```

ping и telnet работают

**Comment by oleshiy** [comment]
Добрый вечер.
Какие параметры указываете при создании драйвера? 
И какой пример используете?

**Comment by mad** [comment]
Пример NameResolverExample.java, параметры ендопоинта и бд меняю на свои из облака

**Comment by oleshiy** [comment]
> Пример NameResolverExample.java, параметры ендопоинта и бд меняю на свои из облака

Можно попросить запустить с вашими параметрами соединения basic_example_v1?
Документация: https://cloud.yandex.ru/docs/ydb/sdk/
Пример: https://github.com/yandex-cloud/ydb-java-sdk/tree/master/examples/src/main/java/com/yandex/ydb/examples/basic_example_v1

**Comment by mad** [comment]
Запустил, тоже самое

```
дек. 08, 2019 10:10:05 ПП io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl handleErrorInSyncContext
WARNING: [Channel<1>: (ydb://lb.etn023606g34quq96vdq.ydb.mdb.yandexcloud.net:2135/ru-central1/b1g4ttmpjol8o9cnvlt3/etn023606g34quq96vdq)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Network closed for unknown reason
unable to resolve database /ru-central1/b1g4ttmpjol8o9cnvlt3/etn023606g34quq96vdq, network issue, cause=null}
com.yandex.ydb.core.UnexpectedResultException: cannot create session, code: TRANSPORT_UNAVAILABLE, issues: [gRPC error: (UNAVAILABLE) Network closed for unknown reason
unable to resolve database /ru-central1/b1g4ttmpjol8o9cnvlt3/etn023606g34quq96vdq, network issue (S_ERROR)]
	at com.yandex.ydb.core.Result$Fail.newException(Result.java:196)
	at com.yandex.ydb.core.Result$Fail.expect(Result.java:154)
	at com.yandex.ydb.examples.basic_example.BasicExampleApp.<init>(BasicExampleApp.java:60)
	at com.yandex.ydb.examples.AppRunner.run(AppRunner.java:53)
	at com.yandex.ydb.examples.basic_example.BasicExampleApp.main(BasicExampleApp.java:526)
```

**Comment by mad** [comment]
Использую примеры из мавена версия 1.3.0, там нет basic_example_v1 , запускал BasicExampleApp

Отличие похоже только в TLS, видимо проблема с этим и связана. Когда ожидать появления 1.4.0 в мавене?

**Comment by mad** [comment]
C TLS подключился, но почему то пример заканчивается с ошибкой

```
...
--[ PreparedSelect ]--
+-------------+------------+-----------+-----------+--------------------------------------+
|    air_date | episode_id | season_id | series_id |                                title |
+-------------+------------+-----------+-----------+--------------------------------------+
| Some[16964] |    Some[8] |   Some[3] |   Some[2] | Some["Bachman's Earnings Over-Ride"] |
+-------------+------------+-----------+-----------+--------------------------------------+
com.yandex.ydb.examples.basic_example_v1.exceptions.TooManyRetriesException
	at com.yandex.ydb.examples.basic_example_v1.BasicExampleV1.execute(BasicExampleV1.java:504)
	at com.yandex.ydb.examples.basic_example_v1.BasicExampleV1.executeWithResult(BasicExampleV1.java:512)
	at com.yandex.ydb.examples.basic_example_v1.BasicExampleV1.multiStep(BasicExampleV1.java:394)
	at com.yandex.ydb.examples.basic_example_v1.BasicExampleV1.run(BasicExampleV1.java:77)
	at com.yandex.ydb.examples.AppRunner.run(AppRunner.java:69)
	at com.yandex.ydb.examples.basic_example_v1.BasicExampleV1.main(BasicExampleV1.java:531)

Process finished with exit code 1
```

**Comment by oleshiy** [comment]
> Использую примеры из мавена версия 1.3.0, там нет basic_example_v1 , запускал BasicExampleApp
> 
> Отличие похоже только в TLS, видимо проблема с этим и связана. Когда ожидать появления 1.4.0 в мавене?

Действительно, подключение по TLS обязательно. 
1.4.0 в ближайшее время опубликуем, спасибо за обратную связь.

**Comment by oleshiy** [comment]
версию 1.4.0 залили в Maven Central http://repo1.maven.org/maven2/com/yandex/ydb/ydb-sdk-table/

**Comment by mad** [comment]
Спасибо, закрываю задачу
